name: cfn-github-actions
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
      inputs:
        name:
          description: "test"
          default: "test"
jobs:
  check-cfn:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install CFN tools
        run: |
          gem install cfn-nag
      - name: CFN Nag scan
        run: |
          cfn_nag_scan --input-path  lambda.yaml
      - name: Install cfn-lint
        run: |
          pip install cfn-lint
      - name: CFN Lint
        run: |
          cfn-lint lambda.yaml
      - name: Install bandit
        run: |
          pip install bandit
      - name: bandit check
        run: |
          bandit -r rss_webhook.py --confidence-level high
